const dragonNames = [
    "XxFlameOfDoomxX", "Dr4gonSw4gg3r", "WingWh1sp3rr", "Sh4dowDrgn420", "FireF4ngMaster", "xDraconicxL0rd", "Bl4zeBl4de666", "Fr0styF1reball", "T4lonT3rror666", "V0lcanicV0y4g3r",
    "Pl4sm4Pr0wler", "WyrmWr4thM4st3r", "V3nomVixen420", "Cry5t4lCrafter", "Twil1ghtT4lon", "G1imm3rG0y1", "DuskDr4g0n666", "Blizz4rdBlast", "Fl4reF4ngM4ster", "MagmaMaj3sty666",
    "Echo3clipseXxX", "Fr0stbiteFury", "S0larSpt3r420", "Abyss4rb1terX", "Thund3rTerror", "St0rmyScl420", "1nf3rn0I5t4tor", "N3cr0t1cNemesis", "Sh4d0w3dSerpent", "Dr34dDrgnSl4y3r",
    "Lun4rLor3Mystic", "R4d1antR4ptor420", "F3roc10usFl4me", "Gl0wingG4laxy", "CrimsonC0met420", "M00nlitM4gician", "A5tralAgs420", "R4gingR0arMaster", "Thund3rboltThrasher", "W4rpW4nd3r3r",
    "Bl4zingBtD3stroy3r", "Sp3ctralS4vage", "V3nomousV1x3n420", "Ph0enixPh3n0m", "Ch40sChmp10n", "V10l3tVpr2000", "Pl4tinumProwess", "C0sm1cC5t4stroph3", "Dr4g0nD3vour3r420", "My5ticalM4ster",
    "Fl4m3Fr0stFury", "Sh4tt3r3dScales", "Wh1sp3rWyv3rn420", "C1nd3rCqrChamp", "V0rt3xVgbV0y4g3r", "3mb3rEtrn4lEmp3ror", "Dr3ad3d_Dr4ke666", "Bl4zingB_D3v1l", "F13ryFng3r420", "W1ck3dWyrmling666",
    "Sh4d0wSftS3rp3nt", "Fr0stbFryF1end", "3n1gmat1cEm3rald", "Sapph1reSerp3nt420", "1nf3rn4lIvory", "ArcaneAbysm4l", "J4d3JggernautX", "Ethr3alEmperor420", "St0rmSurf3r2000", "R4diantRaz3r420",
    "C0sm1cCw4rriorX", "Dr4c0n1cD3l1ght", "Wh1sp3rWyrmW1z", "Thunder_T3mpest420", "Eternal_EmberXx", "4byss4lAsp3ct420", "N0bl3N3crom4ncer", "FrostFury2001", "Ch40sCrlCrusher", "G4l3GrdnGuard",
    "W4rpW3av3rW1zard", "V0rt3xVoy4g3r420", "C3l3stialCh4mp", "RiftRav4ger2000", "D00mDr4keDestroy", "Bl4zingBrimstone", "Twil1ghtTyrantX", "Myst1cMarauderXx", "Fr0stbFng420", "S0larShad0w2000",
    "Sh4d0w3dScalesXx", "0bsidianOracl3", "Thund3r_Tyrant420", "Sp3ctralSerp3ntX", "Whirlw1ndWyv3rn", "Ethr3alEmbraceXx", "Zephyrion", "Nyxalthor", "Aurelian", "Valkorath", "Ignatius", "Drakaina", "Sylphira", "Zephyros", "Aurora", "Nyxeris",
    "Vermithrax", "Glepharion", "Vexethor", "Zypherion", "Cyrilith", "Eldrazor", "Mythoros", "Xeraphas", "Zyraxia", "Zarathos",
    "Aerithia", "Thaloros", "Veridian", "Vorathor", "Khalador", "Phyraxis", "Xandoria", "Necroth", "Sylvaria", "Velorian",
    "Thornax", "Azura", "Vespera", "Lytharion", "Zorathor", "Drogonis", "Aerithrax", "Auroros", "Nyxion", "Xanthea",
    "Zephyrax", "Vexilith", "Aurelion", "Valerian", "Zyphira", "Crimsonis", "Mythoria", "Xyleria", "Zarathorn", "Eldrixis",
    "Drakaris", "Syrenia", "Verinthor", "Xyphoros", "Azurith", "Sylpharion", "Thornasia", "Khaladon", "Phyrexia", "Lytharia",
    "Nyxaria", "Zephyris", "Vexorath", "Aurorium", "Cyrilith", "Veltherion", "Necrosia", "Zarathor", "Aerithas", "Voraxia",
    "Zypherius", "Thaloria", "Valerias", "Zephyrath", "Drakaria", "Sylphoros", "Auroria", "Nyxoria", "Xylerion", "Vermorath",
    "Zyrixis", "Eldrathor", "Aurorath", "Nyxaroth", "Xylixis", "Verorath", "Zarathos", "Sylphoria", "Aerionis", "Thalorius",
    "Voraxius", "Zylerian", "Valoria", "Zephyron", "Aurithrax", "Nyxorath", "Xyphorax", "Verathor", "Zaraxia", "Sylphorax",
    "Drakorian", "Aerithor", "Voraxian", "Zephyria", "Aurorix", "Nyxaria", "Xyloria", "Verithor", "Zarathia", "Sylphoria",
    "Thalorian", "Vorathia", "Zyphoria", "Aurius", "Nyxon", "Xypharion", "Vermorius", "Zaraxor", "Sylphion", "Aerithia", "Michael Jonathan Fredrick Fredrickson Sr Sr Jr Sr Jr Jr Jr Jr Sr Jr III"
  ];